summary:
  path: sshleifer/distilbart-cnn-12-6

textractor:
  join: true
  lines: false
  minlength: 100
  paragraphs: true
  sentences: false

texttospeech:

workflow:
  tts:
    tasks:
      - action: textractor
        task: url
      - action: summary
      - action: texttospeech
